[package]
name = "dbio-protocol"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = "1.0.130"
recrypt = "0.13.1"
pad = "0.1.6"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
