version: "3.9"
services:
  dbio-protocol:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@dbio-postgres/dbio-protocol-db
    ports:
      - 8000:8000

  dbio-postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbio-protocol-db
    ports:
      - 5432:5432
