# This file should be used only when developing code against database
version: "3.9"
services:
  dbio-postgres:
    build: ./migrations
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbio-protocol-db
    ports:
      - 5432:5432
