version: "3.9"
services:
  dbio-postgres:
    container_name: dbio-postgres
    build: ./migrations
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbio-protocol-db
    ports:
      - 5432:5432

  dbio-protocol:
    container_name: dbio-protocol
    #image: ssheldharv/dbio-protocol:latest
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@dbio-postgres/dbio-protocol-db
    ports:
      - 8080:8080
    depends_on:
      - dbio-postgres

  dbio-client:
    container_name: dbio-client
    image: ssheldharv/dbio-client:latest
    ports:
      - 3000:3000
    depends_on:
      - dbio-protocol

  dbio-fhir-proxy:
    container_name: dbio-fhir-proxy
    image: ssheldharv/dbio-fhir-proxy:latest
    ports:
      - 8081:8080
