# This file should be used only when developing code against database
version: "3.9"
services:
  dbio-postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbio-protocol-db
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
