version: "3.9"
services:
  dbio-postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbio-protocol-db
    ports:
      - 5432:5432

