name: Docker Image Build & Release

on:
  push:
    branches: [ trunk, docker-ci-cd ]

env:
  IMAGE_NAME: dbio-protocol
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:password@localhost/dbio-protocol-db

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dbio-protocol-db
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Migrate database
      run: |
        sudo apt-get install pkg-config libssl-dev postgresql libpq-dev -y
        docker ps
        cargo install --version=0.5.11 sqlx-cli --no-default-features --features postgres
        SKIP_DOCKER=true sqlx database create && sqlx migrate run
    - name: Build Crate Executable
      run: cargo build --release
    - name: Build Docker Image
      run: |
        docker build . \
          --tag ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:$GITHUB_SHA \
          --tag ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_KEY }}
    - name: Push Docker image
      run: docker push --all-tags ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME